version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gochecknoinits
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
    - unused
    - whitespace
  settings:
    errorlint:
      errorf: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
