on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x, 1.21.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
    - run: make test
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - uses: actions/checkout@v4
    - run: make verify
  apidiff:
    runs-on: ubuntu-latest
    if: github.base_ref
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Add GOBIN to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: go install golang.org/x/exp/cmd/apidiff@latest
    - name: Checkout old code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        path: "old"
    - name: Checkout new code
      uses: actions/checkout@v4
      with:
        path: "new"
    - name: APIDiff
      run: ./hack/verify-apidiff.sh -d ../old
      working-directory: "new"
